[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_SITE_URL = "https://devrathoreprotfolio.netlify.app"
  NODE_VERSION = "18.17.0"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  included_files = ["node_modules/openai/**/*"] 